### PR TITLE
Fix For False Modifying Bug

### PR DESCRIPTION
**Pull request by dowski**
The bug is that the `_evermod` flag gets set to `True` whenever a repeated field is accessed. See the test in the first commit. It was failing.

This leads to extra work when calling `.dumps()` on truly unmodified protobufs (there's an optimization that just uses the bytes if `_evermod == False`) and also false information when applications make the `modified()` API call on proto objects.

The fix involves a change to the `_set_<name>` method on generated code and the `ProtoBase._get_repeated` method. 

The `_set_<name>` method now takes a `modifying` keyword argument that defaults to `True`. That passes through to `_evermod` so that standard `setattr/__setattr__` behavior continues to set `_evermod = True`.

`ProtoBase._get_repeated` now calls `_set_<name>` with `modifying=False` since it is simply initiating the state for that field and not doing any modifying of the data.

### CODE REVIEW

**Comment by dowski** [comment]
As I was describing the pull request above I noticed a bug in my implementation. Fix coming up and will be integrated with this pull request ...

**Comment by dowski** [comment]
OK, should be good now.

**Comment by dowski** [comment]
I just added a couple more fixes to this pull request. One takes care of an issue that was noted on our internal tracker related to weirdness with `foo__stream` that I also ran into this morning and the other makes sure we record `RepeatedSequence` mutation when dealing with slices (like we do in the `clear()` method).

**Comment by wmoss** [comment]
Looks reasonable to me

**Pull request merged**
